---
- name: Install iperf3 package if not present
  package:
     name: iperf3
     state: present

- name: Open port 5201 for iperf
  firewalld:
     port: '5201/tcp'
     permanent: false
     state: enabled

- set_fact:
     iperf_res: "{{ perfresdir }}/iperf"

- set_fact:
     iperf_duration: "{{gluster_maintenance_iperf_duration|default(30)}}"

- set_fact:
     ping_duration: "{{gluster_maintenance_ping_duration | default(10)}}"

- name: Create directory for iperf result collection
  file:
     path: "{{ iperf_res }}"
     state: directory

- name: Start iperf3 server on all nodes
  shell: |
     nohup iperf3 -s > {{iperf_res}}/iperf3_server_{{inventory_hostname}}.txt\
           </dev/null 2>&1 &
  async: 7200
  poll: 0

- name: Run iperf3 tests
  shell: >
     iperf3 -c {{ item.1 }} -t {{ iperf_duration }} > \
       {{iperf_res}}/iperf3_client_{{ item.1 }}_server_{{ item.0 }}.txt;
     ping -c {{ ping_duration }} {{item.1}} > \
       {{iperf_res}}/ping_client_{{item.1}}_server_{{item.0}}.txt;
  delegate_to: "{{ item.0 }}"
  run_once: true
  when: item.0 != item.1
  with_nested:
     - "{{ gluster_maintenance_net_perf_nodes }}"
     - "{{ gluster_maintenance_net_perf_nodes }}"

- name: Stop iperf3 on all nodes
  command: pkill -x iperf3

- name: Collect the results into a directory
  synchronize:
     src: "{{ iperf_res }}"
     dest: "{{ localresdir }}/"
     dirs: yes
     mode: pull

- debug:
    msg: "Test results are stored in {{localresdir}}"
  run_once: true