---
- set_fact:
     profile_name: 'seq-write'
  run_once: true

- name: Run fio tests
  shell: |
     fio --name=writetest --ioengine=sync --rw=write --direct=0 \
         --create_on_open=1 --end_fsync=1 --bs=128k --directory={{fiodir}} \
         --filename_format=f.\$jobnum.\$filenum \
         --filesize={{gluster_maintenance_fio_size_gb|default(16)}}g \
         --size={{gluster_maintenance_fio_size_gb|default(16)}}g \
         --numjobs={{gluster_maintenance_fio_numjobs|default(16)}} \
         --output={{ profile_name}}.out
  delegate_to: "{{ gluster_maintenance_client }}"
  run_once: true